### ISSUE TITLE
New miner problem

### ISSUE THREAD

**Issue by locohamster** [tedder/helium_hotspot_exporter#3]
When the miner is not fully in sync, its API responses are causing the following error:

helium_hotspot_exporter.py:req_get_json:88:DEBUG        fetch returned: <Response [200]>
Traceback (most recent call last):
  File "/opt/app/helium_hotspot_exporter.py", line 301, in <module>
    stats()
  File "<decorator-gen-1>", line 2, in stats
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/context_managers.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "/opt/app/helium_hotspot_exporter.py", line 289, in stats
    stats_for_hotspot(addr, hname)
  File "/opt/app/helium_hotspot_exporter.py", line 182, in stats_for_hotspot
    HOTSPOT_HEIGHT.labels(addr,hname,'hotspot_current').set(d['status']['height'])
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/metrics.py", line 364, in set
    self._value.set(float(value))
TypeError: float() argument must be a string or a number, not 'NoneType'

If you have multiple miners running OK and you are adding a new one you might lose data due to the termination of the exporter with an exception. 

Some error-handling might be introduced:

Sample API response with private data removed.

{
   "data":{
      "speculative_nonce":1,
      "lng":"CENSORED",
      "lat":"CENSORED",
      "timestamp_added":"2022-01-03T20:04:28.000000Z",
      "status":{
         "timestamp":null,
         "online":"online",
         "listen_addrs":null,
         "height":null
      },
      "reward_scale":null,
      "payer":"CENSORED",
      "owner":"CENSORED",
      "nonce":1,
      "name":"CENSORED",
      "mode":"full",
      "location_hex":"CENSORED",
      "location":"CENSORED",
      "last_poc_challenge":null,
      "last_change_block":1165403,
      "geocode":{
         "short_street":"CENSORED",
         "short_state":"CENSORED",
         "short_country":"CENSORED",
         "short_city":"CENSORED",
         "long_street":"CENSORED",
         "long_state":"CENSORED",
         "long_country":"CENSORED",
         "long_city":"CENSORED",
         "city_id":"CENSORED"
      },
      "gain":12,
      "elevation":0,
      "block_added":1164681,
      "block":1165687,
      "address":"CENSORED"
   }
}

**Comment by locohamster** [comment]
Will try to provide patch.

**Comment by tedder** [comment]
If this is failing, please reopen or open a new ticket.
