### ISSUE TITLE
Script crash

### ISSUE THREAD

**Issue by gigipl** [tedder/helium_hotspot_exporter#7]
helium_hotspot_exporter.py:hotspot_activity_counts:248:DEBUG	{'data': {'vars_v1': 0, 'validator_heartbeat_v1': 0, 'unstake_validator_v1': 0, 'transfer_validator_stake_v1': 0, 'transfer_hotspot_v2': 0, 'transfer_hotspot_v1': 1, 'token_burn_v1': 0, 'token_burn_exchange_rate_v1': 0, 'state_channel_open_v1': 0, 'state_channel_close_v1': 15, 'stake_validator_v1': 0, 'security_exchange_v1': 0, 'security_coinbase_v1': 0, 'routing_v1': 0, 'rewards_v2': 500, 'rewards_v1': 0, 'redeem_htlc_v1': 0, 'price_oracle_v1': 0, 'poc_request_v1': 181, 'poc_receipts_v1': 990, 'payment_v2': 0, 'payment_v1': 0, 'oui_v1': 0, 'gen_gateway_v1': 0, 'dc_coinbase_v1': 0, 'create_htlc_v1': 0, 'consensus_group_v1': 0, 'consensus_group_failure_v1': 0, 'coinbase_v1': 0, 'assert_location_v2': 2, 'assert_location_v1': 0, 'add_gateway_v1': 1}}
helium_hotspot_exporter.py:req_get_json:89:DEBUG	fetching url: https://api.helium.io/v1/hotspots/location/distance?lat=52.3883564622256&lon=17.06427169993496&distance=20000
helium_hotspot_exporter.py:req_get_json:91:DEBUG	fetch returned: <Response [200]>
Traceback (most recent call last):
  File "/opt/app/helium_hotspot_exporter.py", line 326, in <module>
    stats()
  File "<decorator-gen-1>", line 2, in stats
  File "/usr/local/lib/python3.10/site-packages/prometheus_client/context_managers.py", line 81, in wrapped
    return func(*args, **kwargs)
  File "/opt/app/helium_hotspot_exporter.py", line 314, in stats
    stats_for_hotspot(addr, hname)
  File "/opt/app/helium_hotspot_exporter.py", line 232, in stats_for_hotspot
    HOTSPOT_REWARDS.labels(addr, hname, '7d').set(d7['total'])
TypeError: 'NoneType' object is not subscriptable

**Comment by tedder** [comment]
fixed, see #9
